# This playbook deploys a full node from scratch.
---
- name: setup machine
  hosts: validator1
  become: yes
  roles:
  - machine-setup

- name: Setup validator 1
  hosts: validator1
  become: yes
  roles:
    - zeitgeist-node

- name: Setup kusama
  hosts: validator2
  become: yes
  roles:
    - zeitgeist-node